/**
 * Comment Editor Component
 * Read-only generated comment with copy and post functionality
 * Note: Editing disabled to maintain AI-generated content integrity
 */

import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Copy, Check, Sparkles, RefreshCw, Send, AlertCircle } from 'lucide-react'
import styles from './CommentEditor.module.css'

interface CommentEditorProps {
  comment: string
  onRegenerate: () => void
  onPost: () => void
  isPosting: boolean
  isAlreadyPosted: boolean
  hasTranscript: boolean
  processingTime: number | null
  language: 'tr' | 'en'
}

export const CommentEditor: React.FC<CommentEditorProps> = ({
  comment,
  onRegenerate,
  onPost,
  isPosting,
  isAlreadyPosted,
  hasTranscript,
  processingTime,
  language
}) => {
  const [copied, setCopied] = useState(false)

  const t = {
    aiGenerated: language === 'tr' ? 'AI Tarafından Üretildi' : 'AI Generated',
    withTranscript: language === 'tr' ? 'Transcript analizi yapıldı' : 'Transcript analyzed',
    copy: language === 'tr' ? 'Kopyala' : 'Copy',
    copied: language === 'tr' ? 'Kopyalandı!' : 'Copied!',
    regenerate: language === 'tr' ? 'Yeniden Üret' : 'Regenerate',
    post: language === 'tr' ? 'YouTube\'a Gönder' : 'Post to YouTube',
    posting: language === 'tr' ? 'Gönderiliyor...' : 'Posting...',
    alreadyPosted: language === 'tr' ? 'Zaten Gönderildi' : 'Already Posted',
    processingTime: language === 'tr' ? 'saniyede üretildi' : 'generated in',
    disclaimer: language === 'tr'
      ? 'Yorum YouTube\'a gönderildiğinde AI tarafından üretildiğini belirten bir not içerecektir.'
      : 'The comment will include a note indicating it was generated by AI when posted to YouTube.',
    alreadyPostedNote: language === 'tr'
      ? 'Bu videoya zaten bir yorum gönderilmiş. Her videoya yalnızca bir yorum gönderilebilir.'
      : 'A comment has already been posted to this video. Only one comment per video is allowed.'
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(comment)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  return (
    <motion.div
      className={styles.container}
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.2 }}
    >
      {/* Header */}
      <div className={styles.header}>
        <div className={styles.headerLeft}>
          <Sparkles size={16} className={styles.sparkle} />
          <span>{t.aiGenerated}</span>
          {hasTranscript && (
            <span className={styles.transcriptBadge}>
              {t.withTranscript}
            </span>
          )}
        </div>
        {processingTime && (
          <span className={styles.processingTime}>
            {processingTime}s {t.processingTime}
          </span>
        )}
      </div>

      {/* Comment Text */}
      <div className={styles.commentWrapper}>
        {isEditing ? (
          <textarea
            className={styles.textarea}
            value={comment}
            onChange={(e) => onChange(e.target.value)}
            onBlur={() => setIsEditing(false)}
            autoFocus
            rows={6}
          />
        ) : (
          <motion.div
            className={styles.commentText}
            onClick={() => setIsEditing(true)}
            whileHover={{ backgroundColor: 'rgba(255, 215, 0, 0.05)' }}
          >
            {comment}
          </motion.div>
        )}
      </div>

      {/* Actions */}
      <div className={styles.actions}>
        <div className={styles.actionsLeft}>
          <button
            className={styles.actionButton}
            onClick={handleCopy}
            title={t.copy}
          >
            <AnimatePresence mode="wait">
              {copied ? (
                <motion.span
                  key="check"
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  exit={{ scale: 0 }}
                  className={styles.copied}
                >
                  <Check size={16} />
                  {t.copied}
                </motion.span>
              ) : (
                <motion.span
                  key="copy"
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  exit={{ scale: 0 }}
                >
                  <Copy size={16} />
                  {t.copy}
                </motion.span>
              )}
            </AnimatePresence>
          </button>

          <button
            className={styles.actionButton}
            onClick={() => setIsEditing(!isEditing)}
            title={t.edit}
          >
            <Edit3 size={16} />
            {t.edit}
          </button>

          <button
            className={styles.actionButton}
            onClick={onRegenerate}
            title={t.regenerate}
          >
            <RefreshCw size={16} />
            {t.regenerate}
          </button>
        </div>

        <motion.button
          className={styles.postButton}
          onClick={onPost}
          disabled={isPosting}
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
        >
          {isPosting ? (
            <>
              <RefreshCw size={18} className={styles.spinning} />
              {t.posting}
            </>
          ) : (
            <>
              <Send size={18} />
              {t.post}
            </>
          )}
        </motion.button>
      </div>

      {/* Disclaimer */}
      <div className={styles.disclaimer}>
        <AlertCircle size={14} />
        <span>{t.disclaimer}</span>
      </div>
    </motion.div>
  )
}
