'use client'

import React, { useState, useEffect } from 'react'
import type { NextPage } from 'next'
import { motion, AnimatePresence } from 'framer-motion'
import {
  Youtube,
  Sparkles,
  Wand2,
  Loader2,
  AlertCircle,
  CheckCircle,
  Brain,
  Globe,
  MessageSquare,
  Zap,
  Shield,
  Languages
} from 'lucide-react'
import { MainLayout } from '@/components/Layout/MainLayout'
import { useLanguage } from '@/context/LanguageContext'
import { VideoPreview, CommentEditor } from '@/components/CrownCommend'
import {
  useCommend,
  COMMENT_STYLES,
  COMMENT_LANGUAGES,
  type CommentLanguage,
  type CommentStyle
} from '@/hooks/useCommend'
import styles from '@/styles/pages/crown-commend.module.css'

const CrownCommendPage: NextPage = () => {
  const { language } = useLanguage()
  const [mounted, setMounted] = useState(false)

  const {
    state,
    videoUrl,
    language: commentLanguage,
    style,
    generatedComment,
    videoDetails,
    processingTime,
    hasTranscript,
    error,
    postResult,
    isValidUrl,
    setVideoUrl,
    setLanguage: setCommentLanguage,
    setStyle,
    generateComment,
    postComment,
    reset
  } = useCommend()

  useEffect(() => {
    setMounted(true)
  }, [])

  const t = {
    badge: language === 'tr' ? 'YouTube AI Asistanı' : 'YouTube AI Assistant',
    title: language === 'tr' ? 'Crown Commend' : 'Crown Commend',
    subtitle: language === 'tr'
      ? 'Yapay zeka ile YouTube videolarına özgün, yaratıcı ve etkileyici yorumlar üretin.'
      : 'Generate unique, creative and engaging comments for YouTube videos with AI.',
    urlLabel: language === 'tr' ? 'YouTube Video URL' : 'YouTube Video URL',
    urlPlaceholder: language === 'tr'
      ? 'https://youtube.com/watch?v=... veya https://youtu.be/...'
      : 'https://youtube.com/watch?v=... or https://youtu.be/...',
    languageLabel: language === 'tr' ? 'Yorum Dili' : 'Comment Language',
    styleLabel: language === 'tr' ? 'Yorum Stili' : 'Comment Style',
    generateButton: language === 'tr' ? 'Yorum Üret' : 'Generate Comment',
    generating: language === 'tr' ? 'Üretiliyor...' : 'Generating...',
    errorTitle: language === 'tr' ? 'Hata' : 'Error',
    successMessage: language === 'tr'
      ? 'Yorum başarıyla YouTube\'a gönderildi!'
      : 'Comment successfully posted to YouTube!',
    featuresTitle: language === 'tr' ? 'Özellikler' : 'Features',
    features: [
      {
        icon: Brain,
        title: language === 'tr' ? 'Gelişmiş AI' : 'Advanced AI',
        description: language === 'tr'
          ? 'Google Gemini ile video içeriğini analiz eder ve bağlamsal yorumlar üretir.'
          : 'Analyzes video content with Google Gemini and generates contextual comments.'
      },
      {
        icon: Languages,
        title: language === 'tr' ? 'Çoklu Dil' : 'Multi-Language',
        description: language === 'tr'
          ? 'Türkçe, İngilizce, Rusça, Çince ve Japonca dillerinde yorum üretir.'
          : 'Generates comments in Turkish, English, Russian, Chinese and Japanese.'
      },
      {
        icon: MessageSquare,
        title: language === 'tr' ? 'Transcript Analizi' : 'Transcript Analysis',
        description: language === 'tr'
          ? 'Video altyazılarını analiz ederek daha alakalı yorumlar üretir.'
          : 'Analyzes video subtitles to generate more relevant comments.'
      },
      {
        icon: Shield,
        title: language === 'tr' ? 'Şeffaf AI' : 'Transparent AI',
        description: language === 'tr'
          ? 'Tüm yorumlar AI tarafından üretildiğini belirten bir disclaimer içerir.'
          : 'All comments include a disclaimer indicating they were generated by AI.'
      }
    ],
    disclaimer: language === 'tr'
      ? 'Crown Commend, YouTube\'un hizmet şartlarına uygun şekilde çalışır. Üretilen tüm yorumlar AI tarafından oluşturulduğunu belirten bir not içerir. Spam veya kötüye kullanım amaçlı kullanım yasaktır.'
      : 'Crown Commend operates in compliance with YouTube\'s terms of service. All generated comments include a note indicating they were created by AI. Use for spam or abuse is prohibited.'
  }

  if (!mounted) {
    return (
      <MainLayout
        title={language === 'tr' ? 'Crown Commend - AI YouTube Yorum Üretici' : 'Crown Commend - AI YouTube Comment Generator'}
        description={t.subtitle}
        keywords={language === 'tr' ? 'youtube yorum, ai yorum, yapay zeka, commend ai' : 'youtube comment, ai comment, artificial intelligence, commend ai'}
      >
        <div className={styles.commendPage}>
          <div className={styles.commendContainer}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '50vh' }}>
              <Loader2 size={32} className={styles.buttonSpinner} style={{ color: '#ff4444' }} />
            </div>
          </div>
        </div>
      </MainLayout>
    )
  }

  const isLoading = state === 'generating' || state === 'fetching' || state === 'posting'

  return (
    <MainLayout
      title={language === 'tr' ? 'Crown Commend - AI YouTube Yorum Üretici' : 'Crown Commend - AI YouTube Comment Generator'}
      description={t.subtitle}
      keywords={language === 'tr' ? 'youtube yorum, ai yorum, yapay zeka, commend ai' : 'youtube comment, ai comment, artificial intelligence, commend ai'}
    >
      <div className={styles.commendPage}>
        {/* Background */}
        <div className={styles.commendBackground}>
          <div className={styles.commendGradient} />
          <div className={styles.commendPattern} />
        </div>

        <div className={styles.commendContainer}>
          {/* Header */}
          <motion.header
            className={styles.commendHeader}
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className={styles.headerBadge}>
              <Youtube size={16} />
              <span>{t.badge}</span>
            </div>
            <h1 className={styles.commendTitle}>{t.title}</h1>
            <p className={styles.commendSubtitle}>{t.subtitle}</p>
          </motion.header>

          {/* Main Section */}
          <motion.section
            className={styles.mainSection}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            {/* Input Card */}
            <div className={styles.inputCard}>
              {/* URL Input */}
              <div className={styles.inputGroup}>
                <label className={styles.inputLabel}>{t.urlLabel}</label>
                <div className={styles.urlInputWrapper}>
                  <Youtube size={20} className={styles.urlInputIcon} />
                  <input
                    type="text"
                    className={`${styles.urlInput} ${videoUrl ? (isValidUrl ? styles.urlValid : styles.urlInvalid) : ''}`}
                    placeholder={t.urlPlaceholder}
                    value={videoUrl}
                    onChange={(e) => {
                      setVideoUrl(e.target.value)
                      if (generatedComment) reset()
                    }}
                    disabled={isLoading}
                  />
                </div>
              </div>

              {/* Options */}
              <div className={styles.optionsRow}>
                <div className={styles.selectWrapper}>
                  <label className={styles.selectLabel}>{t.languageLabel}</label>
                  <select
                    className={styles.select}
                    value={commentLanguage}
                    onChange={(e) => setCommentLanguage(e.target.value as CommentLanguage)}
                    disabled={isLoading}
                  >
                    {COMMENT_LANGUAGES.map((lang) => (
                      <option key={lang.code} value={lang.code}>
                        {lang.flag} {lang.name}
                      </option>
                    ))}
                  </select>
                </div>

                <div className={styles.selectWrapper}>
                  <label className={styles.selectLabel}>{t.styleLabel}</label>
                  <select
                    className={styles.select}
                    value={style}
                    onChange={(e) => setStyle(e.target.value as CommentStyle)}
                    disabled={isLoading}
                  >
                    {COMMENT_STYLES.map((s) => (
                      <option key={s.id} value={s.id}>
                        {s.name[language]} - {s.description[language]}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              {/* Generate Button */}
              <motion.button
                className={`${styles.generateButton} ${isLoading ? styles.generating : ''}`}
                onClick={generateComment}
                disabled={!isValidUrl || isLoading}
                whileHover={{ scale: isValidUrl && !isLoading ? 1.02 : 1 }}
                whileTap={{ scale: isValidUrl && !isLoading ? 0.98 : 1 }}
              >
                {state === 'generating' ? (
                  <>
                    <Loader2 size={22} className={styles.buttonSpinner} />
                    {t.generating}
                  </>
                ) : (
                  <>
                    <Wand2 size={22} />
                    {t.generateButton}
                  </>
                )}
              </motion.button>
            </div>

            {/* Results Section */}
            <AnimatePresence mode="wait">
              {/* Error */}
              {error && (
                <motion.div
                  key="error"
                  className={styles.errorCard}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -20 }}
                >
                  <AlertCircle size={24} />
                  <div className={styles.errorText}>
                    <div className={styles.errorTitle}>{t.errorTitle}</div>
                    <div className={styles.errorMessage}>{error.message}</div>
                  </div>
                </motion.div>
              )}

              {/* Success Toast (after posting) */}
              {postResult && postResult.status === 'success' && (
                <motion.div
                  key="success"
                  className={styles.successToast}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -20 }}
                >
                  <CheckCircle size={24} />
                  <span className={styles.successText}>{t.successMessage}</span>
                </motion.div>
              )}

              {/* Video Preview */}
              {videoDetails && (
                <motion.div
                  key="video"
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -20 }}
                >
                  <VideoPreview details={videoDetails} language={language} />
                </motion.div>
              )}

              {/* Comment Editor */}
              {generatedComment && (
                <motion.div
                  key="comment"
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -20 }}
                >
                  <CommentEditor
                    comment={generatedComment}
                    onRegenerate={generateComment}
                    onPost={postComment}
                    isPosting={state === 'posting'}
                    isAlreadyPosted={postResult?.status === 'success' || postResult?.alreadyCommented === true}
                    hasTranscript={hasTranscript}
                    processingTime={processingTime}
                    language={language}
                  />
                </motion.div>
              )}
            </AnimatePresence>
          </motion.section>

          {/* Features Section */}
          <motion.section
            className={styles.featuresSection}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.6, delay: 0.4 }}
          >
            <h2 className={styles.featuresTitle}>{t.featuresTitle}</h2>
            <div className={styles.featuresGrid}>
              {t.features.map((feature, index) => (
                <motion.div
                  key={index}
                  className={styles.featureCard}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: 0.5 + index * 0.1 }}
                >
                  <div className={styles.featureIcon}>
                    <feature.icon size={24} />
                  </div>
                  <h3 className={styles.featureTitle}>{feature.title}</h3>
                  <p className={styles.featureDescription}>{feature.description}</p>
                </motion.div>
              ))}
            </div>
          </motion.section>

          {/* Disclaimer Footer */}
          <motion.footer
            className={styles.disclaimerFooter}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.6, delay: 0.8 }}
          >
            <p>{t.disclaimer}</p>
          </motion.footer>
        </div>
      </div>
    </MainLayout>
  )
}

export default CrownCommendPage
